### ISSUE TITLE
Assignment 3 (TwitLite) - Reviews

### ISSUE THREAD

**Issue by giaotuancse** [giaotuancse/TwitLite#1]
Hi @coderschoolreview,
I've just published my assignment, please take a review. Thank you :wink: 
Cause I had some unexpected stuff this weekend so I can't focus on assignment to refine code, change UI, interface for a better application, but almost features of application are there. 
It looks ugly right now but I will commit a better version later. Sorry about this. :smile:

**Comment by coderschoolreview** [comment]
:+1: Nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. 

## Grading Summary
- **Functionality**: Good
- **Code Style**: Good
- **Visual Design**: Good
- **Usability**: Good
- **Overall**: Good

## Detailed Notes

At first, your project cannot be built. The reason is you import `Cartography` in `HomeViewController` though you didn't install `Cartography` pod. Please remember to make sure your project can be built successfully before submitting.

Great things:
- I'm very happy to see that your code style has been improved. That's great! :clap: 
- Nice work specifying the Auto Layout constraints.
- Nice work handling the retweet label by using stack view :dizzy: 
- Nice work handling the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience.

Some small comments:
- You shoud try setting up the controls within the Tweet cells. It can sometimes be hard to have a clean design for embedded controls because it usually involves cumbersome plumbing. This is an instance where I think having the model handle the network action helps greatly simplify the implementation.
- Favorite feature in Detail view doesn't work well. I like a tweet, the heart icon change to red, but the number of favorite doesn't increase. But when I reload from timeline, it's ok.
  <img width="283" alt="screen shot 2015-12-02 at 10 42 21 pm" src="https://cloud.githubusercontent.com/assets/15702670/11535479/b063edf0-9946-11e5-80e0-111082c09784.png">
- You should display something to distinguish normal tweet and reply tweet.
- You should show `name` and `screenname` in tweet cell instead of 2 `screenname` like this
  <img width="315" alt="screen shot 2015-12-02 at 10 55 41 pm" src="https://cloud.githubusercontent.com/assets/15702670/11535751/daccad1a-9947-11e5-932e-df971771d588.png">
- When composing new tweet, if the text is empty, you should disable the button. For now, though you do nothing with empty text when tapping button, but user can still tap it.
- Why did you use `else` block though it's empty? I see it many times in your code

``` Swift
if (bool) {
  // your code
} else {

}
```
- Please notice my comments in your code to improve your code.

Good submission overall. This assignment is pretty hard, congrats on completing it! :star2: It was here to teach you about keeping track of "state" of objects, and also to be the first assignment to accept user input.
